language: c++
dist: trusty
sudo: required
# addons:
#     apt:
#       sources:
#       - ubuntu-toolchain-r-test
#       - kalakris-cmake
#       packages:
#       - cmake
#       - gcc-4.8
#       - g++-4.8
before_install:
  - travis_retry wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_8.0.44-1_amd64.deb
  - travis_retry sudo dpkg -i cuda-repo-ubuntu1404_8.0.44-1_amd64.deb
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -y cuda-drivers cuda-core-8.0 cuda-cudart-dev-8-0 cuda-cufft-dev-8-0
  - travis_retry sudo apt-get clean
  - export CUDA_HOME=/usr/local/cuda-8.0
  - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - export PATH=${CUDA_HOME}/bin:${PATH}
script:
  - mkdir build && cd build && cmake .. -DWITH_CUDA=ON -DWITH_BENCHMARK=ON && make
